- voltron/view.py
Previously, subclasses of VoltronView were broken
> initialize window only in TerminalView

- voltron/core.py
- voltron/plugins/view/register.py
This fixes a bug initially triggered in my environment by getting u'n/a' back in DS. No idea why it is suddenly a `unicode`, but this is a bit more defensive regardless.
> pythonic type coercion

- dbgentry.py
- voltron/core.py
Progame can't run again correctly for setting stop_and_exit_handler as gdb exit event handler
To fix it:
1. Add is_running to Class Server to indicate if a server is running
2. Modify cont_handler to create a new server if server is None or not running
> Fix re-running program in GDB

- voltron/plugins/view/register.py
I was receiving "TypeError: unsupported operand type(s) for +:
'ConfigNode' and 'list'"; this fixes it by converting the first argument to a
list before appending. Also needed to construct the new config_sections
list separately and then assign it to self.config.sections because
self.config.sections.append was being interpreted as a ConfigNode rather
than a method on the self.config.sections list.
> Fix TypeError when passing --no-sse to reg view

- voltron/plugins/debugger/dbg_gdb.py
Similar to the way it's done in get_registers_x86_64, this crashes on platforms where fetching SSE registers doesn't work.
> Also catch sse/fpu register errors for x86

- voltron/dbg.py
Fixes the "Exception getting registers from debugger: name 'target' is not defined" error when remote debugging an arm target with openocd.
> Fixes "name 'target' is not defined" error

- examples/angularview/angularview.py
- voltron/core.py
- voltron/plugins/api/breakpoints.py
- voltron/plugins/api/command.py
- voltron/plugins/api/dereference.py
- voltron/plugins/api/memory.py
- voltron/plugins/api/registers.py
- voltron/plugins/api/targets.py
Many of the errors that Voltron encounters __str__ into an empty string,
but __repr__ into a useful string describing the error.
> repr errors before creating APIGenericErrorResponse's

- voltron/plugins/debugger/dbg_gdb.py
Otherwise, an infinite loop of death may ensue.
> Check for existance of ptr in chain didn't take into account additional layer of tuple around ptr

- setup.py
* pep8-ify setup.py
* Use gdb's python shell to determine the version of python linked to gdb
* Wrap warning text
> setup.py: Wrap text and use more reliable version check

- install.sh
`sed` will complain loudly if the files it's supposed to edit don't exist. This changeset adds a check to prevent the install failing when debugger init scripts are not present.
> Check if gdb/lldb init file exists before sed-ing

- install.sh
This changeset adds a function that will attempt to install the required packages on Fedora/CentOS. `yum` has been recently replaced by `dnf`, but older systems might still use it, so we check if the latter exists and pick the better one. (Even though by default, in newer systems, `yum` is an alias for `dnf`, I preffered not to count on that.)
> Add function to install required packages on Fedora

- install.sh
The issue was even when the python executable already has version information at the end of it, the script was still appending it.
> fix for #193

- install.sh
`--user` will fail inside a virtualenv with the following message:
```
+ /Users/xxx/venv/voltron/bin/python -m pip install -U --user .
Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```
Afaict this doesn't break anything else, and respects the intentions of the user and installer. Tested on macOS 10.12.
> Remove pip user mode when installing in a venv

- voltron/plugins/view/memory.py
This makes it easier to notice and pay attention to nonzero bytes in
memory that's mostly zeroes.
> Style 00 bytes as comments in MemoryView

- voltron/plugins/view/register.py
Fix for [issue 226](https://github.com/snare/voltron/issues/226)
Makes it possible to disable extra info in registers view to get a simple column of register names & values.
Extra info is still on by default, the argument now allows for explicit disabling of extra info.
> Fix for issue 226.  Register view --info option changed to --hide-info

- voltron/plugins/view/memory.py
Renaming the async variable because it is a keyword in new python versions and this breaks voltron.
Fixing Issue #241
> Renaming the async variable

- install.sh
Fix configuration for lldb that ships with newer Xcode's in the following ways:
- Fix `lldb` incantation to split of the -Q -x -b args because the llvm project thought it was really important to break that behavior (this should work on older lldb versions)
- lldb no longer reports python as sys.executable, so we cobble together the best python interpreter from `sys.exec_prefix+"/bin/python”`
- I wasn't able to test on older systems (Sierra) because it doesn't have pip, and you can't easy_install pip due to TLS deprecation, so we `curl` the pip bootstrap script from bootstrap.pypa.io and run that
- The bootstrap script is then somehow able to install pip and dependencies and update our TLS
> Fix lldb 1100.0.28.19

- voltron/plugins/api/__init__.py
For some reason `voltron.plugin.api` wasn't picking up the `xrange = range` done in `voltron/__init__.py`, so let's add that to `voltron/plugin/api/__init__.py`
> fix xrange in voltron.plugin.api

- voltron/plugins/__init__.py
- voltron/plugins/debugger/__init__.py
- voltron/plugins/debugger/dbg_lldb.py
packages don't know their parent package, so we have to explicitly set the xrange alias in more places
> more xrange fixes

- voltron/config/default.cfg
- voltron/plugins/api/memory.py
- voltron/plugins/view/memory.py
- voltron/plugins/view/memstride.py
A simple fix for the annoying behavior with six that parses escape sequences and will stirp any "\" in the memory causing offset issues.
Added the memstride plugin so that you can see a large set of data  change, but also added support to dynamically change the word length, hex/dec, and cols/line with l, h/d, -/=
> Improvements to memory vieweing
